# Generated by Django 5.2.8 on 2025-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_spec_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spec_sheet',
            field=models.FileField(blank=True, help_text='Upload product spec sheet PDF', null=True, upload_to='spec-sheets/'),
        ),
    ]
